// AUTO-GENERATED by generate-aliases.cjs. DO NOT EDIT.
// Direct OpenAPI type references for clarity with API specification
import type { components, paths } from './openapi';

// Direct exports for OpenAPI types
export type { components, paths };

// Union types for enums found in OpenAPI schema
export type Chain = "Cardano" | "Solana" | "Aptos" | "Hedara" | "Polygon" | "Ethereum" | "Bitcoin" | "Unknown";

// Application-specific Union types for mint operations
export type MintReservation = { reservationId: string; state: 'reserved'; txHash?: never };
export type MintedResult   = { state: 'minted'; txHash: string; nftUid: string; reservationId?: string };
export type MintResult     = MintReservation | MintedResult;

// Wallet creation types for endpoints not in OpenAPI schema
export interface CreateWalletResponse {
  address: string;
  walletName: string;
  message?: string;
}

export interface CreateWalletRequest {
  walletName: string;
  enterpriseaddress: boolean;
  walletPassword: string;
}


export const NMKR_CONFIG = {
  DEFAULT_TIMEOUT: 15000,
  MAX_RETRIES: 3,
  RETRY_DELAY_BASE: 1000,
} as const;
