// AUTO-GENERATED by generate-aliases.cjs. DO NOT EDIT.
// Direct OpenAPI type references for clarity with API specification
import type { components, paths } from './openapi';

// Direct exports for OpenAPI types
export type { components, paths };

// Union types for enums found in OpenAPI schema
export type Chain = "Cardano" | "Solana" | "Aptos" | "Hedara" | "Polygon" | "Ethereum" | "Bitcoin" | "Unknown";

// Application-specific Union types for mint operations
export type MintReservation = { reservationId: string; state: 'reserved'; txHash?: never };
export type MintedResult   = { state: 'minted'; txHash: string; nftUid: string; reservationId?: string };
export type MintResult     = MintReservation | MintedResult;

// Wallet creation types for endpoints not in OpenAPI schema
export interface CreateWalletResponse {
  walletAddress: string;
  customerId: number;
  success: boolean;
  message?: string;
}

export interface CreateWalletRequest {
  // Empty for now, as the endpoint appears to only require the customerid path parameter
}

// Subcustomer management types for endpoints not in OpenAPI schema
export interface CreateSubcustomerRequest {
  description: string;
  externalId: string;
}

export interface CreateSubcustomerResponse {
  subcustomerId: number;
  customerId: number;
  description: string;
  externalId: string;
  success: boolean;
  message?: string;
}

export interface CreateApikeyForSubcustomerRequest {
  subcustomerId: number;
  description: string;
  expiryDate: string;
}

export interface CreateApikeyForSubcustomerResponse {
  apiKey: string;
  subcustomerId: number;
  description: string;
  expiryDate: string;
  success: boolean;
  message?: string;
}

export const NMKR_CONFIG = {
  DEFAULT_TIMEOUT: 15000,
  MAX_RETRIES: 3,
  RETRY_DELAY_BASE: 1000,
} as const;
