steps:
  - id: build-server
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - -c
      - >-
        docker build
        --file=Dockerfile
        --tag=gcr.io/$PROJECT_ID/civicship-api
        --build-arg=PROJECT_ID=$$PROJECT_ID
        .
    secretEnv:
      - DATABASE_URL
  - id: push-server
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/civicship-api
  - id: deploy-server
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - civicship-api
      - --image=gcr.io/$PROJECT_ID/civicship-api
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=us-central1
      - --allow-unauthenticated
      - --update-secrets=DATABASE_URL=DATABASE_URL:latest
    waitFor:
      - push-server
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
