steps:
  - id: Build Docker image
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/civicship-api', '.' ]
  - id: Push Docker image to Container Registry
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/civicship-api']
  - id: Deploy to Cloud Run
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', 'civicship-api', '--image', 'gcr.io/$PROJECT_ID/civicship-api', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
