version: '3.8'
services:
  db:
    image: postgres:16.4-alpine3.20
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=civicship_db
    ports:
      - 15432:5432
    volumes:
      # データを永続化するために、名前付きボリュームの割り当てを定義
      - db-data:/var/lib/postgresql/data
      # 起動時に初期設定（テーブル作成 / seeds挿入）などを実行するため、docker-entrypoint-initdb.dにマウント
      - ./container/docker/postgresql/init/:/docker-entrypoint-initdb.d
volumes:
  db-data:
    driver: local