version: '3.8'
services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=civicship_db
    ports:
      - 15432:5432
