name: Deploy External API to Cloud Run (dev)

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-external-api.yml
    with:
      stage: dev
      environment: dev
      node-env: development
      extra-env-vars: |
        ENV=dev
      create-git-tag: false
    secrets: inherit
