name: Deploy Typedoc to Pages

on:
  push:
    branches:
      - feature/update-schema-by-UX
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node.js (npm) をセットアップ
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 依存関係のインストールとドキュメント生成
      - name: Install and build typedoc
        run: |
          npm install
          npm run doc

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 生成された ./docs などのフォルダをアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/typedoc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
